# Generated by Django 5.1.6 on 2025-03-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Enter the city where you live')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Name of city where you live:',
                'verbose_name_plural': 'The names of cities where you live',
            },
        ),
        migrations.CreateModel(
            name='ProgLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Enter your programming language')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Name of programming language which you use',
                'verbose_name_plural': 'The names of programming languages that you use',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Vacancy title')),
                ('company_name', models.CharField(max_length=250, verbose_name='Name of the company')),
                ('description', models.TextField(verbose_name='Vacancy description')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city', verbose_name='City')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proglanguage', verbose_name='Programming Language')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancions',
            },
        ),
    ]
