# Generated by Django 5.1.6 on 2025-03-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proglanguage_alter_city_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Vacancy title')),
                ('company_name', models.CharField(max_length=250, verbose_name='Name of the company')),
                ('description', models.TextField(verbose_name='Vacancy description')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city', verbose_name='City')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proglanguage', verbose_name='Programming Language')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancions',
            },
        ),
    ]
